shellEmulator: true

packages:
  - docs
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

catalogs:
  cli:
    "@bomb.sh/tab": "^0.0.11"
    "@types/minimist": "^1.2.5"
    "@types/nopt": "^3.0.32"
    "@types/text-table": "^0.2.5"
    "@types/update-notifier": "^6.0.8"
    "@types/yargs-parser": "^21.0.3"
    "@uttr/tint": "^0.1.3"
    args-tokens: "^0.23.0"
    fast-string-width: "^3.0.2"
    fastest-levenshtein: "^1.0.16"
    is-platform: "^1.0.0"
    kons: "^0.7.1"
    lite-emit: ^4.0.0
    minimist: "^1.2.8"
    mri: "^1.2.0"
    nopt: "^9.0.0"
    text-table: "^0.2.0"
    type-flag: "^4.0.3"
    update-notifier: "^7.3.1"
    yargs-parser: "^22.0.0"
  dev:
    "@antfu/ni": "^28.2.0"
    "@types/node": "^24.10.9"
    "@typescript/native-preview": "7.0.0-dev.20260118.1"
    "@vitest/coverage-istanbul": "^4.0.17"
    "@vitest/ui": "^4.0.17"
    bumpp: "^10.4.0"
    changelogithub: "^14.0.0"
    eslint: "^9.39.2"
    prettier: "^3.8.0"
    tsdown: "^0.20.0-beta.3"
    typescript: "^5.9.3"
    vite: "^8.0.0-beta.8"
    vite-plugin-simple-tsconfig-alias: "^0.2.0"
    vitest: "^4.0.17"
    vitest-console: "^0.2.1"
  docs:
    "@shikijs/vitepress-twoslash": "^3.21.0"
    oxc-minify: ^0.108.0
    typedoc: "^0.28.16"
    typedoc-plugin-markdown: ^4.9.0
    typedoc-vitepress-theme: ^1.1.2
    unocss: "^66.6.0"
    vitepress: "2.0.0-alpha.15"
    vitepress-plugin-group-icons: "^1.6.9"
    vue-tsc: ^3.2.2
  lint:
    "@so1ve/eslint-config": v4.3.0
    "@so1ve/prettier-config": v4.3.0
