packages:
  - docs
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

catalogs:
  docs:
    "@shikijs/vitepress-twoslash": "^3.19.0"
    oxc-minify: ^0.102.0
    typedoc: "^0.28.15"
    typedoc-plugin-markdown: ^4.9.0
    typedoc-vitepress-theme: ^1.1.2
    unocss: "^66.5.10"
    vitepress: "2.0.0-alpha.15"
    vitepress-plugin-group-icons: "^1.6.5"
    vue-tsc: ^3.1.8
